cache:
    directories:
        - $HOME/perl_modules
os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y cmake cmake-data ninja-build python3-pip ack-grep cpanminus perl libdb5.3-dev libgd-dev libperl-dev libxml2-dev lynx valgrind vim wml
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
install:
    - which python3
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm App::XML::DocBook::Builder Pod::Xhtml YAML::XS
    - cpanm HTML::T5
    - cpanm Class::XSAccessor File::Copy::Recursive File::Find::Object::Rule HTML::Widgets::NavMenu::EscapeHtml IO::All MooX MooX::late Path::Tiny QuadPres Task::QuadPres Text::VimColor Template Test::Trap XML::LibXML
    - cpanm Dist::Zilla Pod::Weaver::Section::Support
    # For wml
    - cpanm Bit::Vector Carp::Always Class::XSAccessor GD Getopt::Long IO::All Image::Size Term::ReadKey
    # For quadp
    - cpanm Class::XSAccessor Config::IniFiles HTML::Links::Localize
    - perl CI-testing/continuous-integration-testing.pl install_deps
    - bash scripts/install-git-cmakey-program-system-wide.bash 'git' 'src' 'https://github.com/thewml/website-meta-language.git'
perl:
    - "5.26"
python:
    - "3.6"
script: perl CI-testing/continuous-integration-testing.pl test
