cache:
    directories:
        - $HOME/perl_modules
# dist: trusty
# dist: xenial
dist: bionic
os: linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y ack-grep cmake cmake-data cpanminus libdb5.3-dev libgd-dev libgdbm-dev libgdbm-compat-dev libperl-dev libxml2-dev lynx ninja-build perl python3-pip valgrind vim wml
install:
    - which python3
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - perl -V
    - which cpanm
    - "install_deps_whose_tests_are_stalling() { cpan HTTP::Daemon ; } ; install_deps_whose_tests_are_stalling ;"
    # - "install_deps_whose_tests_are_stalling() { cpanm --notest HTTP::Daemon ; } ; install_deps_whose_tests_are_stalling ;"
perl:
    - "5.26"
python:
    - "3.6"
script: perl CI-testing/continuous-integration-testing.pl test
