#!/usr/bin/perl -w

use strict;

my @perl_scripts=
(
    qw(fix-gvim-html.pl render-file.pl)
);

open O, ">Makefile.am";
print O <<'EOF' ;
# WARNING! This Makefile was generated by gen_am.pl.
# Do not modify directly!!!
include $(top_srcdir)/perl5/Shlomif/modules.am

PATH_PERL = @PATH_PERL@

qpscriptsdir = $(pkgdatadir)/scripts/

EOF

print O "qpscripts_SCRIPTS = " . join(" ", @perl_scripts) . "\n\n";

foreach my $script (@perl_scripts)
{
    print O "${script}: $script.pl Makefile\n";
    print O "\tcat ${script}.pl | " .
        "sed 's!{QP_MODULES_DIR}!\$(modulesdir)!g' | " .
        "sed '1 s!/usr/bin/perl!\$(PATH_PERL)!' " .
        "> $script\n";
    print O "\tchmod 755 ${script}\n";
    print O "\n";
}

print O "EXTRA_DIST = " . join(" ", (map { "$_.pl" } @perl_scripts)) . "\n\n";

print O "EXTRA_DIST += gen_am.pl\n\n";

print O "\n\n";

close(O);

